# Generated by Django 4.1.3 on 2022-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
