# Generated by Django 4.1.3 on 2022-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='usersVote',
            field=models.TextField(blank=True),
        ),
    ]
